/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package architecture;

import javax.swing.JOptionPane;

/**
 *
 * @author Qaffas
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        insarea = new javax.swing.JTextArea();
        start = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        bl = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        bv = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        location = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        value = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mips Simulator");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Run");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, 190, 50));

        insarea.setColumns(20);
        insarea.setRows(5);
        jScrollPane1.setViewportView(insarea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 1030, 269));

        start.setText("0");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });
        getContentPane().add(start, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 11, 65, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Please enter starting address:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Enter Instructions:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 56, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Value");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 410, -1, -1));

        bl.setColumns(20);
        bl.setRows(5);
        jScrollPane2.setViewportView(bl);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 390, 200, 50));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Location");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 410, -1, -1));

        bv.setColumns(20);
        bv.setRows(5);
        jScrollPane3.setViewportView(bv);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 390, 190, 50));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Add Bytes to Memory");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Add Words to Memory");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Location");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));

        location.setColumns(20);
        location.setRows(5);
        jScrollPane4.setViewportView(location);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 200, 50));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Value");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, -1, -1));

        value.setColumns(20);
        value.setRows(5);
        jScrollPane5.setViewportView(value);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, 190, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
        int startingAddress = Integer.parseInt(start.getText());
        int n = insarea.getLineCount();
        Instructions[] ins = new Instructions[n];
        try{
        Instructions.Setpc(startingAddress);
        }
        catch(Exception e){JOptionPane.showMessageDialog(null, "Starting Address must be positive and divisible by 4!", "ERROR!",JOptionPane.WARNING_MESSAGE);
         return;
        }
         for (int i = 0; i < n; i++){
             try{
                 
           int start = insarea.getLineStartOffset(i);
                int end = insarea.getLineEndOffset(i);
                
                String input= insarea.getText(start, end-start);
                ins[i]=new Instructions(input);
            ins[i].Setic(startingAddress + i*4);
             }
             catch(Exception e){JOptionPane.showMessageDialog(null, "Please Enter valid 32 bits instructions","Error",JOptionPane.WARNING_MESSAGE);
             return;
             }
            
        }
         Mem_Reg.registers[29]=1048576;
       // Mem_Reg.addValuesToMemory();
           int am = location.getLineCount();
         for(int i=0;i<am;i++){
             try{
         
             int begin = location.getLineStartOffset(i);
             int end = location.getLineEndOffset(i);
             int begin2 = value.getLineStartOffset(i);
             int end2 = value.getLineEndOffset(i);
             if(i!=am-1){
                 end-=1;
                 end2-=1;
             }
             
             int loc= Integer.parseInt(location.getText(begin, end-begin));
             int val= Integer.parseInt(value.getText(begin2, end2-begin2));
             
             Mem_Reg.addWord(loc, val);
         
         }
             catch(Exception e){
                 
             }
             
         }   
             int amb = bl.getLineCount();
         for(int i=0;i<amb;i++){
            
              try{    
             int begin = bl.getLineStartOffset(i);
             int end = bl.getLineEndOffset(i);
             int begin2 = bv.getLineStartOffset(i);
             int end2 = bv.getLineEndOffset(i);
             if(i!=amb-1){
                 end-=1;
                 end2-=1;
             }
             int locb= Integer.parseInt(bl.getText(begin, end-begin));
             int valb= Integer.parseInt(bv.getText(begin2, end2-begin2));
              
              
             Mem_Reg.addByte(locb, valb);
              } 
              catch(Exception e){
                  
              }
       }
         
             
         
    try{
       while(Instructions.getpc()<=ins[n-1].getic() && Instructions.getpc()>=startingAddress){
           
           for(int i=0;i<ins.length;i++)
           {
           if(ins[i].getic()==Instructions.getpc()){
               try{
               ins[i].execute();
               }
               catch(Exception e){
                   Instructions.Setpc(-4);
                    break;
               }
             //  System.out.println(ins[i].ccregisters[4]);
               ins[i].w.SetWires(ins[i]);
               ins[i].r.setReg(ins[i]);
           }
         }
       }
               DataPath d = new DataPath();
               d.setVisible(true);
    }
    catch(Exception e){
        JOptionPane.showMessageDialog(null, "Please enter an instruction or more", "ERROR!",JOptionPane.WARNING_MESSAGE);
        
    }
       
       
        
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea bl;
    private javax.swing.JTextArea bv;
    private javax.swing.JTextArea insarea;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea location;
    private javax.swing.JTextField start;
    private javax.swing.JTextArea value;
    // End of variables declaration//GEN-END:variables
}
